webtalk_init -webtalk_dir /home/cztery/fpga_censor/censor_axi/censor_axi.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Aug 29 12:25:28 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8e2a7563-ca03-4805-8fb5-c17342deab7a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dfbbc5a0e28c46f8b06a339263afd613" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "55" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1570.109 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "41 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "27" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.84_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "136820_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3413554803 -regid "" -xml /home/cztery/fpga_censor/censor_axi/censor_axi.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cztery/fpga_censor/censor_axi/censor_axi.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cztery/fpga_censor/censor_axi/censor_axi.sim/sim_1/behav/xsim/xsim.dir/mb_design_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
