# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_design/mb_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design || ORIG_REF_NAME==mb_design} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_clk_wiz_1_0/mb_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_clk_wiz_1_0 || ORIG_REF_NAME==mb_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_rst_clk_wiz_1_100M_0/mb_design_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_axi_periph_0/mb_design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_xbar_0/mb_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_xbar_0 || ORIG_REF_NAME==mb_design_xbar_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_0_0/mb_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_0_0 || ORIG_REF_NAME==mb_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_0_1/mb_design_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_0_1 || ORIG_REF_NAME==mb_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_0_2 || ORIG_REF_NAME==mb_design_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_2_0/mb_design_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_2_0 || ORIG_REF_NAME==mb_design_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_1/mb_design_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_1 || ORIG_REF_NAME==mb_design_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_v10_1/mb_design_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_dlmb_v10_1 || ORIG_REF_NAME==mb_design_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_v10_1/mb_design_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_ilmb_v10_1 || ORIG_REF_NAME==mb_design_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_bram_if_cntlr_1/mb_design_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_design_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_1/mb_design_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_design_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_lmb_bram_1/mb_design_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_lmb_bram_1 || ORIG_REF_NAME==mb_design_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_mdm_1_1/mb_design_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_mdm_1_1 || ORIG_REF_NAME==mb_design_mdm_1_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_uart16550_0_0/mb_design_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_axi_uart16550_0_0 || ORIG_REF_NAME==mb_design_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_censor_ip_0_0/mb_design_censor_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_censor_ip_0_0 || ORIG_REF_NAME==mb_design_censor_ip_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_clk_wiz_1_0_1/mb_design_clk_wiz_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_clk_wiz_1_0 || ORIG_REF_NAME==mb_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_lmb_bram_0/mb_design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_lmb_bram_0 || ORIG_REF_NAME==mb_design_lmb_bram_0} -quiet] -quiet

# XDC: bd/mb_design/mb_design_ooc.xdc
