# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio_constraints.xdc

# Block Designs: bd/mb_design/mb_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design || ORIG_REF_NAME==mb_design} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_censor_ip_0_0/mb_design_censor_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_censor_ip_0_0 || ORIG_REF_NAME==mb_design_censor_ip_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_processing_system7_0_0/mb_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_processing_system7_0_0 || ORIG_REF_NAME==mb_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_rst_ps7_0_50M_0/mb_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==mb_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_xbar_0/mb_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_xbar_0 || ORIG_REF_NAME==mb_design_xbar_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ps7_0_axi_periph_1/mb_design_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_ps7_0_axi_periph_1 || ORIG_REF_NAME==mb_design_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_0/mb_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_0 || ORIG_REF_NAME==mb_design_auto_pc_0} -quiet] -quiet

# XDC: bd/mb_design/mb_design_ooc.xdc
